### ISSUE TITLE
api questions

### ISSUE THREAD

**Issue by max-mapper** [jenslind/electron-positioner#1]
```
positioner('topRight', browserWindow)
```

does calling this actually change the `browserWindow` position? also does it return anything or is the idea you would call `positioner` with a different position later if you wanna position it somewhere else?

```
positioner('trayCenter', [200, 200], trayBounds)
```

is this supposed to also position the window? im kinda confused about what this method does since you don't pass a browser window into it... maybe having separate method names rather than 1 overloaded method would make the API easier to understand?

**Comment by max-mapper** [comment]
ah I just saw the line `If you just passing an array, {x,y} will be returned.`. IMO having it be 1 method is pretty confusing

**Comment by max-mapper** [comment]
maybe call them `.move` and `.calculate`

**Comment by max-mapper** [comment]
also what do you think of this API:

```
var createPositioner = require('electron-positioner')
var positioner = createPositioner(browserWindow)
positioner.move('bottomRight')
positioner.move('topLeft')
var xy = positioner.calculate('center')
```

that way `positioner` can be passed around and re-used later more easily

**Comment by jenslind** [comment]
Yepp, thats a good idea to separate the move and the return, will be easier to use.
:+1: for the API.
