### ISSUE TITLE
Position window next to the tray area (Windows)

### ISSUE THREAD

**Issue by black-snow** [jenslind/electron-positioner#3]
Hi,

how do I position a window right next to the tray area (just like dropbox does it)?
I can't use the `*left` and `*right` props for I don't know where the user's task bar is located (left, right, top or bottom). `TrayCenter` and `TrayBottomCenter` don't fit either. (E. g. `trayCenter` sets the window half off-screen (topleft corner) when I have the task bar on the left (win 10).)

Also `npm test` fails with the message that the command `standard` is unkown. Had to look up and install _standard_ globally. Shouldn't this be a dependency on the project rather than being required globally?

**Comment by jenslind** [comment]
Hello,
Currently there is no support for this but I would like to add support for something like this, not sure if it is possible to get the task bars position with node though?

Related issue: https://github.com/maxogden/menubar/issues/80

`npm test` should work after a `npm install`.

**Comment by black-snow** [comment]
Didn't find a way to get the taskbar's position/size built into electron.
I created an issue for this: https://github.com/atom/electron/issues/4010

**Comment by black-snow** [comment]
@jenslind I added a new position `trayAreaWindows` that does what I need pretty well. See comments in the PR for more info: https://github.com/jenslind/electron-positioner/pull/4

I'm open for other names or other approaches.

**Comment by dmythro** [comment]
+1

**Comment by redders6600** [comment]
I'm not sure whether this is likely to be more or less accurate, but I was thinking about doing this myself by using `window.screen` from within a renderer process, and comparing `availHeight` and `availWidth` with `width` and `height`. Combined with some knowledge of the OS, you might then be able to infer the location of the system tray?

![image](https://cloud.githubusercontent.com/assets/2893500/15551360/7c5e1d28-22ad-11e6-8065-1d9d23dbbaee.png)

**Comment by 0x61726b** [comment]
Not sure if I'm understanding wrong but, you can get tray bounds using the Tray object from `require('electron')`

Below output is from Win10 on 1920x1080 display.

```
{Tray} = require('electron')

tray = new Tray('icon/path');

// tray.getBounds() when the taskbar located bottom
// { x: 1696, y: 1040, width: 24, height: 40 }

// tray.getBounds() when the taskbar located top
// { x: 1696, y: 0, width: 24, height: 40 }

// tray.getBounds() when the taskbar located left
// { x: 9, y: 909, width: 24, height: 24 }

// tray.getBounds() when the taskbar located right
// { x: 1863, y: 909, width: 24, height: 24 }
```

**Comment by junwatu** [comment]
@arkenthera thanks it works.

**Comment by ar414-com** [comment]
```javascript
const { Tray, screen } = require('electron');

...

const trayPosition = tray.getBounds();
const screenSize = screen.getPrimaryDisplay().size;
if(trayPosition.y < screenSize.height / 2){
    console.log('top');
}else if(trayPosition.x > -100 && trayPosition.x < screenSize.width / 2){
    console.log('left');
}else if(trayPosition.y > screenSize.height / 2){
    console.log('bottom');
}else if((trayPosition.x >= screenSize.width / 2) && trayPosition.x < screenSize.width){
    console.log('right');
}
```

**Comment by 9oelM** [comment]
For the people who are wondering around the web for the actual code:
https://github.com/maxogden/menubar/blob/master/src/util/getWindowPosition.ts#L18
